### ISSUE TITLE
trace mysql  span is  null  

### ISSUE THREAD

**Issue by guangmingchen** [openzipkin/sleuth-webmvc-example#13]
Span span = ThreadLocalSpan.CURRENT_TRACER.next();    span   is null

**Comment by codefromthecrypt** [comment]
I presume you ran https://github.com/openzipkin/sleuth-webmvc-example#mysql-tracing and didn't get any spans? I will run it and post the result on https://gitter.im/spring-cloud/spring-cloud-sleuth

**Comment by codefromthecrypt** [comment]
Please try the example, as I just did and it worked. The link in the README has a path to the code which is connected to mysql and makes an image like this in the UI.

<img width="995" alt="screen shot 2018-05-25 at 3 00 27 pm" src="https://user-images.githubusercontent.com/64215/40528588-65318dba-602c-11e8-8e0a-a6bf0d205892.png">

**Comment by guangmingchen** [comment]
This example can run normally. I wonder if there is something wrong with my spring boot version (the spring boot version is 1.5.9). Only the spring boot version is 2.0 can mysql-tracing be used correctly？

**Comment by codefromthecrypt** [comment]
yes this doesn't work with spring boot 1.5 as brave integration isn't here
until spring boot 2

**Comment by guangmingchen** [comment]
Thank you. I would like to ask, if I use spring boot 1.5, what solution can I trace mysql？

**Comment by codefromthecrypt** [comment]
you could make a similar interceptor code using the tracer api from spring
cloud sleuth 1.3

this might imply static injection

**Comment by guangmingchen** [comment]
Many thanks

**Comment by codefromthecrypt** [comment]
no problem!
