### ISSUE TITLE
Can't run the acceptance tests from Jenkins

### ISSUE THREAD

**Issue by marcingrzejszczak** [openzipkin/sleuth-webmvc-example#15]
With the changes to docker containers from @abesto I started seeing the following exception when running the scripted acceptance tests:

```
08:52:17 
Creating docker_frontend_1 ... done

Creating zipkin            ... done

Creating docker_backend_1  ... done
the input device is not a TTY
08:52:17 Fail #1/10... will try again in [5] seconds
08:52:23 the input device is not a TTY
08:52:23 Fail #2/10... will try again in [5] seconds
08:52:29 the input device is not a TTY
08:52:29 Fail #3/10... will try again in [5] seconds
08:52:35 the input device is not a TTY
08:52:35 Fail #4/10... will try again in [5] seconds
08:52:41 the input device is not a TTY
08:52:41 Fail #5/10... will try again in [5] seconds
08:52:46 the input device is not a TTY
08:52:46 Fail #6/10... will try again in [5] seconds
08:52:52 the input device is not a TTY
08:52:52 Fail #7/10... will try again in [5] seconds
08:52:58 the input device is not a TTY
08:52:58 Fail #8/10... will try again in [5] seconds
08:53:04 the input device is not a TTY
08:53:04 Fail #9/10... will try again in [5] seconds
08:53:09 the input device is not a TTY
08:53:09 Fail #10/10... will try again in [5] seconds
08:53:09 Failed to start the app...
08:53:10 Killing docker_backend_1  ... 
08:53:10 Killing docker_frontend_1 ... 
08:53:10 Killing zipkin            ... 
08:53:11 
Killing docker_frontend_1 ... done

Killing docker_backend_1  ... done

Killing zipkin            ... done
Build step 'Execute shell' marked build as failure
08:53:14 Finished: FAILURE
```

Obviously, the problematic line is `the input device is not a TTY`. Has anybody noticed such an issue on their side?

**Comment by abesto** [comment]
Oh wow. I didn't realize the scripts are used in environments other than local testing and CircleCI. I could reproduce the issue by running `./scripts/runAcceptanceTests.sh < /dev/null`.

This smells like https://github.com/docker/compose/issues/5696. Indeed running as `env COMPOSE_INTERACTIVE_NO_CLI=1 ./scripts/runAcceptanceTests.sh < /dev/null` seems to trigger the error mentioned in https://github.com/docker/compose/issues/5696#issuecomment-403605760.

Adding `-T` to the `docker_exec` function in `scripts/runAcceptanceTests.sh` such that it reads

```sh
function docker_exec() {
    local SERVICE="$1"; shift
    our_docker_compose exec -T "$SERVICE" "$@"
}
```

seems to work here (running as `./scripts/runAcceptanceTests.sh < /dev/null`, not setting the long weird ENV var).

@marcingrzejszczak can you check that on your Jenkins setup (specifically: changing the function in the script, but not adding the ENV var or `< /dev/null`)? If you can confirm it works, I'll raise a PR.

**Comment by marcingrzejszczak** [comment]
> Oh wow. I didn't realize the scripts are used in environments other than local testing and CircleCI. I could reproduce the issue by running ./scripts/runAcceptanceTests.sh < /dev/null.

We have most of our samples scripted :)

@abesto I can't verify it without actually adding the `-T` over here ;) So maybe let's just add it and see if it fixes our Jenkins builds.

**Comment by abesto** [comment]
Slightly confused here – what's keeping you from actually adding the `-T` for a test run on your Jenkins system? Either way, I'm mostly confident about this, so opened the PR.

**Comment by marcingrzejszczak** [comment]
Works like a charm!
