### ISSUE TITLE
the compatibility problem about dubbo tracing filter

### ISSUE THREAD

**Issue by maoling** [openzipkin/sleuth-webmvc-example#20]
I test the [dubbo tracing instrument](https://github.com/openzipkin/sleuth-webmvc-example/tree/add-dubbo-tracing) and it's ok because it uses the denpendency is
```
<dependency>
      <groupId>com.alibaba.spring.boot</groupId>
      <artifactId>dubbo-spring-boot-starter</artifactId>
      <version>2.0.0</version>
</dependency>
```
but this dubbo version has not been maintained,and now offical version is 
```
<dependency>
      <groupId>com.alibaba.boot</groupId>
      <artifactId>dubbo-spring-boot-starter</artifactId>
      <version>0.2.0</version>
</dependency>
```
when use this one,the [brave](https://github.com/openzipkin/brave/tree/master/instrumentation/dubbo-rpc) may not adapt to it and can not trace the PRC call chain which I have tested.
Appendix:
https://mvnrepository.com/artifact/com.alibaba.boot/dubbo-spring-boot-starter/0.2.0
https://mvnrepository.com/artifact/com.alibaba.spring.boot/dubbo-spring-boot-starter/2.0.0
https://github.com/alibaba/dubbo-spring-boot-starter
https://github.com/apache/incubator-dubbo-spring-boot-project
https://github.com/apache/incubator-dubbo-spring-boot-project
https://github.com/alibaba/dubbo-spring-boot-starter

**Comment by codefromthecrypt** [comment]
yeah the official was not complete when we wrote this example. if you can
help fix that would be great

**Comment by maoling** [comment]
haha,dubbo is very fuckable.

**Comment by maoling** [comment]
ping @beiwei30 @mercyblitz

**Comment by maoling** [comment]
I guess this issue caused from the version of dubbo at first,but upgrade to the lasted `2.6.5`,this rpc call 
chain cannot be traced by 

> <dependency>
      <groupId>com.alibaba.boot</groupId>
      <artifactId>dubbo-spring-boot-starter</artifactId>
      <version>0.2.0</version>
</dependency>

@adriancole  Do you have any insight?

**Comment by codefromthecrypt** [comment]
@maoling thanks for the context. I am preparing for a meetup tomorrow and we have a workshop on the new UI tomorrow and friday. I will try not to forget to look into this saturday. if I do, please ping ok?

**Comment by maoling** [comment]
sir,take it easy!you are the model worker of zipkin(grin)
----- 原始邮件 -----
发件人：Adrian Cole <notifications@github.com>
收件人：openzipkin/sleuth-webmvc-example <sleuth-webmvc-example@noreply.github.com>
抄送人：毛蛤丝 <maoling199210191@sina.com>,  Mention <mention@noreply.github.com>
主题：Re: [openzipkin/sleuth-webmvc-example] the compatibility problem about dubbo tracing filter (#20)
日期：2018年12月05日 19点53分

@maoling thanks for the context. I am preparing for a meetup tomorrow and we have a workshop on the new UI today and tomorrow. I will try not to forget to look into this saturday. if I do, please ping ok?

&mdash;

**Comment by codefromthecrypt** [comment]
@maoling PS tell me if you like this interview https://mp.weixin.qq.com/s/5RSMfBT0vU8CWdc7Dx9jPg

**Comment by maoling** [comment]
@adriancole good reference.awesome!

**Comment by codefromthecrypt** [comment]
ok I just verified the existing demo still works even if it is not the 0.2.0 variant. I will look at that now

**Comment by codefromthecrypt** [comment]
I look and the latest unpublished starter doesn't have much different https://github.com/apache/incubator-dubbo-spring-boot-project/compare/0.2.0

looking at 0.2.0 now

**Comment by codefromthecrypt** [comment]
ok try again. I fixed the branch and raised a couple issues on the new plugin. Nothing is critical
