### ISSUE TITLE
branch add-mysql-tracing not showing any jdbc spans in zipkin

### ISSUE THREAD

**Issue by joannbrereton** [openzipkin/sleuth-webmvc-example#22]
I just pulled the add-mysql-tracing.   The only thing I've changed is the username and password for the mysql database.   Ran it, it traces the /api endpoint but shows no mysql spans.  

Does this require root access for mysql?

**Comment by astik** [comment]
Looking up to https://github.com/openzipkin/brave/tree/master/instrumentation/mysql documentation, this instrumentation uses "statementInterceptors" parameter on the datasource URL:

```
spring.datasource.url=jdbc:mysql://localhost:3306?useSSL=false&statementInterceptors=brave.mysql.TracingStatementInterceptor
```

Fact is, statementInterceptors is supported on MySQL connector 5.1 (https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-interceptors.html) but not on latest version (https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-interceptors.html).
As it does not exist anymore, the parameter is not used anymore and it is like there is no parameter at all : interceptor is not set.

2 solutions :
- easy one : downgrade MySQL connector version inside pom.xml :
```
<dependency>
	<groupId>mysql</groupId>
	<artifactId>mysql-connector-java</artifactId>
	<version>5.1.48</version>
</dependency>
```

- more difficult : write a new version of the instrumentation using newest version 8 interceptors. Good news, Adrian has done that already : https://github.com/openzipkin/brave/tree/master/instrumentation/mysql8 ;  so you can change the instrumentation :

```
    <dependency>
      <groupId>io.zipkin.brave</groupId>
      <artifactId>brave-instrumentation-mysql8</artifactId>
    </dependency>
```
I'll go for second approach =P

Other approach, you can give a try to P6Spy : https://github.com/openzipkin/brave/tree/master/instrumentation/p6spy. I have no idea which one is better.

**Comment by codefromthecrypt** [comment]
heh actually @anuraaga made those interceptors. it is high time we just
update the branch and say mysql 8 is required

**Comment by astik** [comment]
I'll work on updating branch if you want, can do this today.

**Comment by codefromthecrypt** [comment]
thanks.. when you raise the PR, raise it against the mysql branch, not master

**Comment by astik** [comment]
@adriancole this issue should be fixed thanks to 0e4dc83.

**Comment by codefromthecrypt** [comment]
cheers thanks for the reminder

**Comment by codefromthecrypt** [comment]
and of course fixing it :D
