### ISSUE TITLE
Add Spring Kafka Tracing example

### ISSUE THREAD

**Issue by timtebeek** [openzipkin/sleuth-webmvc-example#24]
Hi! Spring Kafka instrumentation has improved since the last two example branches to include out of the box support for Spring Kafka (following https://github.com/spring-cloud/spring-cloud-sleuth/issues/1001) and Kafka Streams (following https://github.com/spring-cloud/spring-cloud-sleuth/pull/1365, pending 2.2.0.M1).

While this project already contains two kafka branches, these seem outdated or have a different scope:
- https://github.com/openzipkin/sleuth-webmvc-example/tree/add-kafka-tracing (duplicates Sleuth instrumentation)
- https://github.com/openzipkin/sleuth-webmvc-example/tree/kafka (span reporting over kafka)

As suggested by @adriancole in spring-cloud/spring-cloud-sleuth#1365 I've added a sample here to show Spring Kafka instrumentation and use:
https://github.com/openzipkin/sleuth-webmvc-example/compare/master...timtebeek:add-spring-kafka-tracing

Not really sure how to target a new branch through a fork/pull request, but perhaps you can help out there. :) Once Sleuth 2.2.0.M1 is out I can provide a similar example (or expand this one) to include Kafka Streams.

**Comment by timtebeek** [comment]
And attached here is a screenshot of this instrumentation, since most branches seem to update that as well.
![Screenshot from 2019-06-16 18-05-06](https://user-images.githubusercontent.com/1027334/59566497-64dddd80-9061-11e9-9497-dda08e701817.png)

**Comment by codefromthecrypt** [comment]
looks good. only thing I might suggest changing is the dockerfile to use
our demo image of kafka as it is simpler that layering the two, notably the
config is a lot simpler also.

https://github.com/openzipkin/docker-zipkin/blob/master/docker-compose-kafka.yml

Also, I forgot to change the base images to lens. It would be nice to lens
in your image.

Once you are ready, I will make a branch and cherry-pick your commit into
it, and delete my old branch.

Cheers! cc @jeqo @imflog

**Comment by timtebeek** [comment]
Ok; I've applied `openzipkin/zipkin-kafka` in the docker-compose file in my branch. Could not get the `backend` and `frontend` services to boot with `docker-compose up`, but that could just be a local issue.

> Also, I forgot to change the base images to lens. It would be nice to lens in your image.

Not entirely sure what you mean by that; I feel my branch is pretty close to what's requested, just don't know how to connect the final dots. Feel free to adopt/adapt as needed. :)

**Comment by jeqo** [comment]
Thanks @timtebeek 
Looks good to me.

About Lens, is our new UI. There should be a button at the top of the Zipkin UI to try it:
![bilde](https://user-images.githubusercontent.com/6180701/59661872-138e3500-91ac-11e9-82bc-733617b706f8.png)

If not available, we can fix it on the PR.

**Comment by timtebeek** [comment]
Ah thanks for the context! :) Here's a new screenshot using Lens; I'll update my branch to use it.
![Screenshot using Lens UI](https://user-images.githubusercontent.com/1027334/59665623-8cdd5600-91b3-11e9-8631-011afd72912b.png)

**Comment by codefromthecrypt** [comment]
merged it in as https://github.com/openzipkin/sleuth-webmvc-example/compare/add-kafka-tracing thanks tons!

**Comment by timtebeek** [comment]
Perfect, thanks! Glad to help! :)
