### ISSUE TITLE
Working with JMS ActiveMQ (add-jms-tracing branch no longerup-to-date)

### ISSUE THREAD

**Issue by astik** [openzipkin/sleuth-webmvc-example#25]
Hi,

When trying the add-jms-tracing branch, i've got this issue at startup for both application (backend and frontend) :

```
***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'configureTracing', defined in class path resource [org/springframework/cloud/sleuth/instrument/messaging/TraceMessagingAutoConfiguration$SleuthJmsConfiguration.class], could not be registered. A bean with that name has already been defined in sleuth.webmvc.JmsTracingConfiguration and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true
```

Adding this configuration inside application.properties makes it work :

```
spring.sleuth.messaging.jms.enabled=false
```

I was wondering if this is the way to go or maybe if sleuth.version is outdated (2.1.0.BUILD-SNAPSHOT on this branch and 2.1.2.RELEASE on master).

I have tested with no change on code, only modifications on application.properties :
- spring.activemq.broker-url to match my broker url
- spring.zipkin.baseUrl to match my zipkin url
- spring.sleuth.messaging.jms.enabled=false to turn off the error as startup

With this, i'm able :
- to send message to the queue after calling frontend api
- to observe the message reaching the queue (active mq from docker webcenter/activemq)
- to observe producer processing the message
- to observe beautiful graphic into zipkin

Also, i don't know if it is normal or not but my message get processed twice.

**Comment by marcingrzejszczak** [comment]
Can't you just change the name of the configuration?

**Comment by codefromthecrypt** [comment]
sorry I think I should have deleted that branch! the only branches intended
to be used are in the readme. this one was made before sleuth already
supported jms

**Comment by astik** [comment]
Ok, so i try working with minimum code to make it communicate from frontend to message queue and then from message queue to backend. Here are the results (starting with master branch as reference - commit id 8f45c78) :

```java
package sleuth.webmvc;

import java.util.Date;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.jms.annotation.EnableJms;
import org.springframework.jms.core.JmsTemplate;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@EnableAutoConfiguration
@RestController
@CrossOrigin // So that javascript can be hosted elsewhere
@EnableJms
public class Frontend {

  @Autowired JmsTemplate jmsTemplate;

  @RequestMapping("/") public void callBackend() {
    jmsTemplate.convertAndSend("backend", new Date());
  }

  public static void main(String[] args) {
    SpringApplication.run(Frontend.class,
        "--spring.application.name=frontend",
        "--server.port=8081"
    );
  }
}
```

```java
package sleuth.webmvc;

import javax.jms.Message;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.jms.annotation.EnableJms;
import org.springframework.jms.annotation.JmsListener;
import org.springframework.web.bind.annotation.RestController;

@EnableAutoConfiguration
@RestController
@EnableJms
public class Backend {

  @JmsListener(destination = "backend")
  public void onMessage(Message m) {
    System.err.println(m);
  }

  public static void main(String[] args) {
    SpringApplication.run(Backend.class,
        "--spring.application.name=backend",
        "--server.port=0" // so that multiple consumer can run on the same server
    );
  }
}
```

Inside pom.xml, i just add : 
```xml
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-activemq</artifactId>
    </dependency>
```

In application.properties, i add 2 parameters to connect to my environment (zipkin and message queue) : 
```
spring.activemq.broker-url=tcp://p-nan-roseau:61616
spring.zipkin.baseUrl: http://p-nan-roseau:9411/
```

That's all ! It's amazing as simple it is to make everything work together. Great job there ! Thanks a lot.

**Comment by codefromthecrypt** [comment]
thanks for closing the loop and glad it is working out!

**Comment by astik** [comment]
Even if it is a very simple use cas, i think it would be interesting to have it in this example project =)

Also, i think it would be easier to have it as a monorepo instead of branch, it would be easier to test new version for spring, sleuth, zipkin.

**Comment by codefromthecrypt** [comment]
this being an example and all want to resist temptation to do too much here
as we have tons of things to manage as it is. you can imagine how big a
repo that would become.. also diff is important to visualize the small
changes.

on this JMS part though.. if you want you can raise PR to change the branch
here including readme update (with image) then we can make your work the
default on the jms branch changing it from accident to official
