### ISSUE TITLE
branch add-rabbit-tracing: how to transfer trace context by rabbitMQ

### ISSUE THREAD

**Issue by xiaoshi100086** [openzipkin/sleuth-webmvc-example#30]
hello~ i use rabbitMQ in my code. And i want to use 'brave' to trace program.

i want to know how to transfer trace conttext by rabbitMQ.

is it  headers?
But transferring trace context by rabbitMQ‘s headers destructive rabbitMQ‘s Headers Exchange characteristic

**Comment by codefromthecrypt** [comment]
can you ask again here please? https://gitter.im/openzipkin/zipkin

**Comment by jeqo** [comment]
Closing as discussion moved to gitter.
