### ISSUE TITLE
WebFlux no RraceId in logs for reponse using JettyClient

### ISSUE THREAD

**Issue by MelC5325** [openzipkin/sleuth-webmvc-example#37]
Using the sleuth-webmvc-example with Jetty HttpClient as per example from  https://www.baeldung.com/spring-log-webclient-calls (point 4.1) for customized logging purposes. Getting the following:
1) First logging output on executing the frontend controller the logging from the RequestLogEnhancer for both the request (request.onRequestxxx) and the response (reqeust.onResponsexxx) contains no trace id in the logs
 eg: 2020-05-17 12:03:16.919  INFO [frontend,,,] 18616 --- [   @298b64f7-67] 

2) After the first attempt executing the frontend controller there after it appears only the response logging has no trace id and the request logging have trace id information eg: 2020-05-17 12:10:06.562  INFO [frontend,5ec080de84f5b416f3397e3cc503c6e1,f3397e3cc503c6e1,false] 9496 --- [io-8081-exec-10]

Enabled debug and all debug logs have the trace ids in them, only the logging I implemented for Jetty HttpClient logging gives issues with point 1 and 2 above. Any help would be appreciated.

Configuration: 
org.springframework.boot 2.2.7.RELEASE 
springCloudVersion  Hoxton.SR4
spring-cloud-starter-sleuth
spring-boot-starter-web and spring-boot-starter-webflux included

**Comment by codefromthecrypt** [comment]
since there's a flux example here: https://github.com/openzipkin/sleuth-webmvc-example/compare/add-webflux-tracing

can you try that and verify before switching anything else? It is usually best to establish base case.. ex. does the default flux example work? Then, try to change it to be like blog if you need to use Jetty client instead of reactor.

**Comment by MelC5325** [comment]
Yes I am using the https://github.com/openzipkin/sleuth-webmvc-example/compare/add-webflux-tracing and the logs have trace ids included. 
Now add Jetty HttpClient with the RequestLogEnhancer from example here https://www.baeldung.com/spring-log-webclient-calls (point 4.1) 

Note only difference is the Jetty HttpClient is used as a connector on the webclient and log request and response headers and content in RequestLogEnhancer  eg:

        HttpClient httpClient  httpClient = new HttpClient() {
            @Override
            public Request newRequest(URI uri) {
                Request request = super.newRequest(uri);
                return new RequestLogEnhancer ().trace(request);
            }
        };
        WebClient webClient = WebClient.builder()
            .clientConnector(new JettyClientHttpConnector(httpClient))
            .baseUrl(backendBaseUrl)
            .build();

All logs printed out in the RequestLogEnhancer does not include the TraceIds all other debug logs do?

**Comment by MelC5325** [comment]
This is what the logs look like when I add the Jetty HttpClient with the Request LogEnhancer: See the INFO line no trace ids, not sure why this happens and we need the trace ids. Appreciate the help. 

2020-05-17 14:10:24.581 DEBUG [frontend,5ec09d1083823e08ff7bd3c679db1132,ff7bd3c679db1132,false] 18424 --- [ctor-http-nio-3] s.w.r.r.m.a.RequestMappingHandlerMapping : [cbc6a5b2-1] Mapped to sleuth.webmvc.Frontend#callBackend()
2020-05-17 14:10:24.608 DEBUG [frontend,5ec09d1083823e08ff7bd3c679db1132,ff7bd3c679db1132,false] 18424 --- [ctor-http-nio-3] o.s.w.r.r.m.a.ResponseBodyResultHandler  : Using 'text/plain;charset=UTF-8' given [*/*] and supported [text/plain;charset=UTF-8, text/event-stream, text/plain;charset=UTF-8, */*]
2020-05-17 14:10:24.608 DEBUG [frontend,5ec09d1083823e08ff7bd3c679db1132,ff7bd3c679db1132,false] 18424 --- [ctor-http-nio-3] o.s.w.r.r.m.a.ResponseBodyResultHandler  : [cbc6a5b2-1] 0..1 [java.lang.String]
2020-05-17 14:10:24.661 DEBUG [frontend,5ec09d1083823e08ff7bd3c679db1132,ff7bd3c679db1132,false] 18424 --- [ctor-http-nio-3] o.s.w.r.f.client.ExchangeFunctions       : [33c67336] HTTP GET http://localhost:9000/api
2020-05-17 14:10:24.720  **INFO [frontend,,,]** 18424 --- [   @31c628e7-55] s.webmvc.logging.RequestLogEnhancer      : 
Request GET http://localhost:9000/api
Accept-Encoding: gzip
User-Agent: Jetty/9.4.28.v20200408
X-B3-TraceId: 5ec09d1083823e08ff7bd3c679db1132
X-B3-SpanId: a0ca0181940cc4f9
X-B3-ParentSpanId: ff7bd3c679db1132
X-B3-Sampled: 0
Accept: */*

**Comment by codefromthecrypt** [comment]
ok this is good info. thank you

**Comment by MelC5325** [comment]
@adriancole do you have any ideas on how to resolve this for us?

**Comment by MelC5325** [comment]
Tested on version 2.2.7 spring boot.

When constructing the Jetty HttpClient injecting the MDC context on each of the listeners used/triggered for logging resolves the missing trace-id issue when using the logging solutions found from here: https://www.baeldung.com/spring-log-webclient-calls (point 4.1).
Try this and construct the Jetty HttpClient 

```java
   Map mdc = MDC.getCopyOfContextMap();
       SslContextFactory sslContextFactory = new SslContextFactory();
        org.eclipse.jetty.client.HttpClient httpClient = new org.eclipse.jetty.client.HttpClient() {
            @Override
            public Request newRequest(URI uri) {
                Request request = super.newRequest(uri);
                request.onRequestBegin(req ->MDC.setContextMap(mdc));
                request.onResponseBegin(response -> MDC.setContextMap(mdc));
                //request.onXXX for any other methods used
                return new RequestLogEnhancer().enhance(request);
            }
        }; 

//....
 WebClient webClient = WebClient.builder()
            .clientConnector(new JettyClientHttpConnector(httpClient))
            .baseUrl(myurl)
            .build();
```

**Comment by codefromthecrypt** [comment]
sorry I took some days off. Glad you figured it out, though wow.. seems laborious! good research and thanks for sharing.
